# MACHINE LEARNING - IA SUPERVISADA

In [1]:
#https://scikit-learn.org/stable/
#git: https://github.com/scikit-learn/scikit-learn/blob/main/doc/datasets/loading_other_datasets.rst
#archivo de data: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/breast-cancer

# TEORIA

In [2]:
#Machine learning Chp5 pag20

import pandas as pd
from IPython.core.display import HTML

from sklearn.datasets import load_breast_cancer

datos=load_breast_cancer()
datos

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
help(datos)
#bunch -> multi indexing , contenedor de keys
#https://stackoverflow.com/questions/56286221/what-is-the-difference-between-bunch-and-dictionary-type-in-python

Help on Bunch in module sklearn.utils object:

class Bunch(builtins.dict)
 |  Bunch(**kwargs)
 |  
 |  Container object exposing keys as attributes.
 |  
 |  Bunch objects are sometimes used as an output for functions and methods.
 |  They extend dictionaries by enabling values to be accessed by key,
 |  `bunch["value_key"]`, or by an attribute, `bunch.value_key`.
 |  
 |  Examples
 |  --------
 |  >>> from sklearn.utils import Bunch
 |  >>> b = Bunch(a=1, b=2)
 |  >>> b['b']
 |  2
 |  >>> b.b
 |  2
 |  >>> b.a = 3
 |  >>> b['a']
 |  3
 |  >>> b.c = 6
 |  >>> b['c']
 |  6
 |  
 |  Method resolution order:
 |      Bunch
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __dir__(self)
 |      Default dir() implementation.
 |  
 |  __getattr__(self, key)
 |  
 |  __init__(self, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __setattr__(self, key, value)
 |      Implement setattr(self, name, value).
 |  
 |  __se

In [4]:
print(datos.DESCR)#describe -> descripcion

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [5]:
df_x=pd.DataFrame(datos["data"])#eje x o variable independiente
display(HTML(df_x.to_html()))


In [6]:
df_y=pd.DataFrame(datos["target"])#eje y o variable dependiente
display(HTML(df_y.to_html()))

# esto lo hago para que entendamos la teoria

In [7]:
print("los datos(pacientes) son: ",len(datos.data)) #recordemos que data es el numero de pacientes
#nota
#del total  de 569 valores observados, se deben dividir los datos para el entrenamiento de la IA (supervisada)
#y la evaluacion en 7:3 u 8:2 -> por defecto la libreria lo hace en 7,5:2.5
#son los porcentajes de datos que le doy a mi IA para que aprenda

los datos(pacientes) son:  569


In [8]:
#por defecto la libreria lo hace en 7,5:2.5 osea 0.75:0.25 osea 75%:25%
data_split_max=len(datos.data)*0.75 # saco el 75% de los datos
data_split_min=len(datos.data)*0.25 # saco el 75% de los datos
print("data_split_max :",data_split_max)
print("data_split_min :",data_split_min)

data_split_max : 426.75
data_split_min : 142.25


# continuando el ejemplo

In [9]:
from sklearn.model_selection import train_test_split
help(train_test_split)


Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to 

In [10]:
#hago un split para asignar os valores de los respectivos ejes x & y que se enviaran para el 
#entrenamiento de la IA

#train son el 75% de la data que sacamos
#test son el 25% de la data para testear

x_train,x_test,y_train,y_test=train_test_split(datos.data,datos.target)
print(len(x_train))
print(len(x_test))

426
143


# RECAPITULANDO EL EJEMPLO # COMPLETO

In [11]:
#NOTA: 3 pasos : 
#    1:instanciar
#        1.1:definir el modelo
#    2:fit ->ajustar
#    3:predecir    

#para instanciar, utilice el hiperparametro del modelo como argumento.
#el hiperparametro es una opcion que REQUIERE CONFIGURACION HUMANA (AI SUPERVISADA!!!!!!!!)
#afecta MUCHO al rendimiento del modelo

#recapitulando el ejemplo

import pandas as pd
from IPython.core.display import HTML

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier #ver en la webpage : https://scikit-learn.org/stable/modules/tree.html#classification

#cargar los datos 
datos=load_breast_cancer()
#instanciar el estimador y ajustar los parametros
x_train,x_test,y_train,y_test=train_test_split(datos.data,datos.target)

#inicializacion del modelo de arbol(ramificacion) mediante entropia 
model=DecisionTreeClassifier(criterion="entropy")


# MODELO FIT (modelo de ajuste)
### Utilice el metodo de ajuste(FIT) con el estimador de instancia para el entrenamiento
### envie los datos  de entrenamiento y los datos de etiqueta juntos como argumento
###  al  algoritmo de aprendizaje  (IA) SUPERVISADO

In [12]:
#OJO!!!!! AQUI ESTA APRENDIENDO :D
model.fit(x_train,y_train) #le mando los datos de train para que entrene y aprenda
#fit ajusta los datos para crear un modelo (regresion) que pueda predecir los datos

# predecir
#aqui le mando el test para ver si si aprendio
y_pred=model.predict(x_test) #le mando los datos de test para que ejecute y observar si si aprendio


#nota
#el estimador de instancia que ha completado el entrenamiento con el ajuste(fit) puede aplicarse
#con el metodo predecir
#predict() convierte los resultados estimados del modelo respecto  a los datos de prueba

y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [13]:
#nota
#Es un valor estimado!!!!, por lo que el valor real de x_test puede variar
#para verificar podemos medir la presicion comparando los valores

In [14]:
y_pred=model.predict(x_test)
pred_2d=y_pred.reshape(len(y_pred),1)#recordemos que y_pred son los datos predecidos
pred_2d

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
    

In [15]:
#y_pred :son los datos predecidos f(x_test)
#y_test :son los resultados VERDADEROS!!!!!

y_test_2d=y_test.reshape(len(y_test),1)
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [16]:
#para observar con facilidad los junto
df_pred=pd.DataFrame(pred_2d) #predecidos
df_true=pd.DataFrame(y_test_2d)#verdaderos
df_concat=pd.concat([df_pred,df_true],axis=1)
df_concat.columns=["pred","true"]
display(HTML(df_concat.to_html()))

# comprobamos la eficiencia de mi IA

In [17]:
#busco los casos de exito de la IA, la prediccion fue correcta

df_exito=df_concat[df_concat["pred"]==df_concat["true"]]#muestra solo donde son iguales
display(HTML(df_exito.to_html()))

In [18]:
exito=len(df_exito)
print(exito)
total_datos=len(df_concat)
print(total_datos)

eficiencia=exito/total_datos
print("la eficiencia de la IA es:",eficiencia*100,"%")

137
143
la eficiencia de la IA es: 95.8041958041958 %
